magic/config/routes.rb
Magic::Application.routes.draw do

  resources :logins

  resources :options do
    member do
      get "register_tournament"
    end
  end

  resources :filters

  resources :comments do
    member do
      get "view_comment"
      get "add_comment"
      post "save_comment"
    end
  end

  resources :members do
    member do
      get "view_member"
    end
  end

  resources :districts
  resources :members

  resources :comments
  resources :tournaments

  resources :locals

  resources :users

  resources :districts

  get 'login' => 'users#login'

  match "filter_by_local" => "options#filter_by_local"
  match "filter_by_status" => "options#filter_by_status"
  match "filter_by_capacity" => "options#filter_by_capacity"

  match "validate_access" => "logins#validate_access"

end

magic/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :user

	validates :tournament_id, :presence => true
	validates :user_id, :presence => true
    validates_uniqueness_of :tournament_id, :scope => :ganador
	
end

magic/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def view_comment
    $current_tournament = Tournament.find(params[:id])

    @comments = Comment.where(:tournament_id => $current_tournament.id)
  end

  def add_comment
    @comment = Comment.new
  end

  def save_comment
    @comment = Comment.new(params[:comment])
    @comment.tournament_id = $current_tournament.id
    @comment.user_id = User.find_by_nombreusuario($user.nombre).id

    @comment.save
  end
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

magic/app/helpers/comments_helper.rb
module CommentsHelper
end

magic/app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%  f.error_notification %>

  <div class="field">
     <%= f.text_area :comentario %>
  </div>
  <div class="field">
    <%= f.label :calificacion %>
   <%= f.select :calificacion, [['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] %>
  </div>
  <div class="field">
    <%= f.association  :tournament %>
  </div>
  <div class="field">
 
    <%= f.association  :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

magic/app/views/comments/add_comment.html.erb
<h1>Tournament's Comment</h1>

<br>

<p>
  	Current tournament: <b><%= $current_tournament.name %></b>
</p>

<p>
    Current User: <b><%= User.find_by_nombreusuario($user.nombre).nombreusuario + ' ' + User.find_by_nombreusuario($user.nombre).paterno %></b>
</p>

<%= form_for(@comment, :url => "save_comment") do |f| %>
  <div class="field">
    <%= f.label "Comment" %><br />
    <%= f.text_area :comentario %>
  </div>
  <div class="actions">
    <%= submit_tag "Add comment" %>
  </div>
<% end %>

magic/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

magic/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>

    <th>Tournament</th>
    <th>User</th>
    <th>Comment</th>
    <th>Calification</th>
    <th>Replica</th>
    <th>Calificator</th>
    <th>Rejoinder</th>

    <th>Comentario</th>
    <th>Calificacion</th>
    <th>Tournament</th>
    <th>User</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>

    <td><%= comment.tournament.nombre %></td>
    <td><%= comment.user.nombre + ' ' + comment.user.paterno + ' ' + comment.user.materno %></td>

    <td><%= comment.comentario %></td>
    <td><%= comment.calificacion %></td>
    <td><%= comment.tournament.name %></td>
    <td><%= comment.user.name %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

magic/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

magic/app/views/comments/save_comment.html.erb
<p>
	Your comment has been saved.
</p>

magic/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comentario:</b>
  <%= @comment.comentario %>
</p>

<p>
  <b>Calificacion:</b>
  <%= @comment.calificacion %>
</p>

<p>
  <b>Tournament:</b>
  <%= @comment.tournament %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

magic/app/views/comments/view_comment.html.erb
<h1>Listing tournament's comments</h1>

<br>

<p>
  Current tournament: <b><%= $current_tournament.name %></b>
</p>

<p>
  Current User: <b><%= User.find_by_nombreusuario($user.nombre).nombreusuario + ' ' + User.find_by_nombreusuario($user.nombre).paterno %></b>
</p>

<table border="1">
  <tr>
    <th>Comment</th>
    <th>Author</th>
    <th>Calification</th>
    <th>Replica</th>
    <th>Calificator</th>
    <th>Rejoinder</th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comentario %></td>
    <td><%= comment.user.nombre + ' ' + comment.user.paterno + ' ' + comment.user.materno %></td>
    <td><%= comment.calificacion %></td>
    <td><%= comment.replica %></td>
    <td><%= comment.calificador %></td>
    <td><%= comment.duplica %></td>
    <td>Calificate</td>
  </tr>
<% end %>
</table>

<br />

<p>
  Total comments: <b><%= @comments.count %></b>
</p>

<br>

<%= link_to 'New Comment', add_comment_comment_path %>