magic/config/routes.rb
Magic::Application.routes.draw do

  resources :logins

  resources :options do
    member do
      get "register_tournament"
    end
  end

  resources :filters

  resources :comments do
    member do
      get "view_comment"
      get "add_comment"
      post "save_comment"
    end
  end

  resources :members do
    member do
      get "view_member"
    end
  end

  resources :districts
  resources :members

  resources :comments
  resources :tournaments

  resources :locals

  resources :users

  resources :districts

  get 'login' => 'users#login'

  match "filter_by_local" => "options#filter_by_local"
  match "filter_by_status" => "options#filter_by_status"
  match "filter_by_capacity" => "options#filter_by_capacity"

  match "validate_access" => "logins#validate_access"

end

magic/app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :local
end

magic/app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def register_tournament
    @tournament = Tournament.find(params[:id])

    @member = Member.new
    @member.tournament_id = @tournament.id
    @member.user_id = User.find_by_nombreusuario($user.nombre).id

    if !Member.find_by_tournament_id_and_user_id(@tournament.id, User.find_by_nombreusuario($user.nombre).id)
      if @tournament.cantregis + 1 > @tournament.cant_part
        @tournament_message = "The tournament is complete."
      else
        @tournament.cantregis += 1
        @tournament.save

        @member.save

        @tournament_message = "The member was registered successfully."
      end
    else
        @tournament_message = "The member already is registered in this tournament."
    end
  end

  def filter_by_local
    @option = Option.new(params[:option])

    @tournaments = Tournament.where(:local_id => @option.local_id)
   end

  def filter_by_status
    @option = Option.new(params[:option])

    @tournaments = Tournament.where(:estado => @option.estado)
  end

  def filter_by_capacity
    @tournaments = Tournament.where("cantregis != cant_part")
  end

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
    $option = Option.new
 @tournaments = Tournament.all
  @tournament = Tournament.new(params[:tournament])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
       format.json { render json: @tournaments }
    end
 
    
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end
end

magic/app/helpers/options_helper.rb
module OptionsHelper
end

magic/app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :opcion %><br />
    <%= f.text_field :opcion %>
  </div>
  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

magic/app/views/options/display_tournament.html.erb
<h1>Listing selected tournaments</h1>

<br>

<p>
	<%= $option.opcion %>
</p>

<p>
Current User: <b><%= User.find_by_name($user.name).name + ' ' +User.find_by_name($user.name).paterno %></b>
</p>

<table border="1">
	<tr>
		<th>Name</th>
	    <th>Local</th>
    	<th>Capacity</th>
    	<th>Players</th>
	    <th>Date and Time</th>
    	<th>Status</th>
    	<th></th>
    	<th></th>
    	<th></th>
	</tr>
<% @tournaments.each do |tournament|%>
	<tr>
		<td><%= tournament.name %></td>
		<td><%= tournament.local.name %></td>
		<td align="center"><%= tournament.cant_part %></td>
		<td><%= tournament.fecha_hora %></td>
		<td><%= tournament.estado %></td>
		<td>
		<% if tournament.cantregis != tournament.cant_part %>
			<%= link_to 'Participate', register_tournament_option_path(tournament) %>
		<% else %>
			Complete
		<% end %>
		</td>
    	<td>
		<% if tournament.cantregis != 0 %>
			<%= link_to 'View members', view_member_member_path(tournament) %>
		<% else %>
			No members
		<% end %>
    	</td>
		<td>
			Comment soon
		</td>
	<tr>
<% end %>
</table>

<p>
	Total tournaments: <%= @tournaments.count %>
</p>

<%= link_to 'Back', options_path %>

magic/app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

magic/app/views/options/filter_by_capacity.html.erb
<h1>Listing selected tournaments by capacity</h1>

<br>

<p>
	Current User: <b><%= User.find_by_nombreusuario($user.nombre).nombreusuario + ' ' + User.find_by_nombreusuario($user.nombre).paterno %></b>
</p>

<p>
</p>

<table border="1">
	<tr>
		<th>Name</th>
	    <th>Local</th>
    	<th>Capacity</th>
    	<th>Players</th>
	    <th>Date and Time</th>
    	<th>Status</th>
    	<th></th>
    	<th></th>
    	<th></th>
	</tr>
<% @tournaments.each do |tournament|%>
	<tr>
		<td><%= tournament.name %></td>
		<td><%= tournament.local.name %></td>
		<td align="center"><%= tournament.cant_part %></td>
		<td align="center"><%= tournament.cantregis %></td>
		<td><%= tournament.fecha_hora %></td>
		<td><%= tournament.estado %></td>
		<td>
		<% if tournament.cantregis != tournament.cant_part %>
			<%= link_to 'Participate', register_tournament_option_path(tournament) %>
		<% else %>
			Complete
		<% end %>
		</td>
    	<td>
			<% if tournament.cantregis != 0 %>
				<%= link_to 'View members', view_member_member_path(tournament) %>
			<% else %>
				No members
			<% end %>
    	</td>
		<td>
			<%= link_to 'Comments', view_comment_comment_path(tournament) %>
		</td>
	<tr>
<% end %>
</table>

<p>
	Total tournaments: <%= @tournaments.count %>
</p>

<%= link_to 'Back', options_path %>

magic/app/views/options/filter_by_local.html.erb
<h1>Listing selected tournaments by local</h1>

<br>

<p>
	Current User: <b><%= User.find_by_nombreusuario($user.nombre).nombreusuario + ' ' + User.find_by_nombreusuario($user.nombre).paterno %></b>
</p>

<p>
</p>

<table border="1">
	<tr>
		<th>Name</th>
	    <th>Local</th>
    	<th>Capacity</th>
    	<th>Players</th>
	    <th>Date and Time</th>
    	<th>Status</th>
    	<th></th>
    	<th></th>
    	<th></th>
	</tr>
<% @tournaments.each do |tournament|%>
	<tr>
		<td><%= tournament.name %></td>
		<td><%= tournament.local.name %></td>
		<td align="center"><%= tournament.cant_part %></td>
		<td align="center"><%= tournament.cantregis %></td>
		<td><%= tournament.fecha_hora %></td>
		<td><%= tournament.estado %></td>
		<td>
		<% if tournament.cantregis != tournament.cant_part %>
			<%= link_to 'Participate', register_tournament_option_path(tournament) %>
		<% else %>
			Complete
		<% end %>
		</td>
    	<td>
			<% if tournament.cantregis != 0 %>
				<%= link_to 'View members', view_member_member_path(tournament) %>
			<% else %>
				No members
			<% end %>
    	</td>
		<td>
			<%= link_to 'Comments', view_comment_comment_path(tournament) %>
		</td>
	<tr>
<% end %>
</table>

<p>
	Total tournaments: <%= @tournaments.count %>
</p>

<%= link_to 'Back', options_path %>

magic/app/views/options/filter_by_status.html.erb
<h1>Listing selected tournaments by status</h1>

<br>

<p>
	Current User: <b><%= User.find_by_nombreusuario($user.nombre).nombreusuario + ' ' + User.find_by_nombreusuario($user.nombre).paterno %></b>
</p>

<p>
</p>

<table border="1">
	<tr>
		<th>Name</th>
	    <th>Local</th>
    	<th>Capacity</th>
    	<th>Players</th>
	    <th>Date and Time</th>
    	<th>Status</th>
    	<th></th>
    	<th></th>
    	<th></th>
	</tr>
<% @tournaments.each do |tournament|%>
	<tr>
		<td><%= tournament.name %></td>
		<td><%= tournament.local.name %></td>
		<td align="center"><%= tournament.cant_part %></td>
		<td><%= tournament.fecha_hora %></td>
		<td><%= tournament.estado %></td>
		<td>
		<% if tournament.cantregis != tournament.cant_part %>
			<%= link_to 'Participate', register_tournament_option_path(tournament) %>
		<% else %>
			Complete
		<% end %>
		</td>
    	<td>
			<% if tournament.cantregis != 0 %>
				<%= link_to 'View members', view_member_member_path(tournament) %>
			<% else %>
				No members
			<% end %>
    	</td>
		<td>
			<%= link_to 'Comments', view_comment_comment_path(tournament) %>
		</td>
	<tr>
<% end %>
</table>

<p>
	Total tournaments: <%= @tournaments.count %>
</p>

<%= link_to 'Back', options_path %>

magic/app/views/options/index.html.erb
<h1>Listing searching options</h1>
<style type="text/css">

  .searchs{
    width: 307px;
    float:left;
    padding:20px;
    color:blue;
  }

  #table tr td{
    padding: 10px;
    width: 100px;
  }
</style>

<br>

<p>
</p>
<div class="searchs">
<%= form_for($option, :url => "filter_by_local") do |f| %>
    <table border="0">
      <tr>
        <td width="150">
          Search by local
        </td>
        <td width="150">
          <%= f.collection_select :local_id, Local.all, :id, :name, :prompt => false %>
        </td>
      </tr>
    </table>
    <%= submit_tag "Search" %>
<% end %>
</div>
<br>

<div class="searchs">
<%= form_for($option, :url => "filter_by_status") do |f| %>
    <table border="0">
      <tr>
        <td width="150">
          Search by status
        </td>
        <td width=150>
            <%= f.select :estado, [['Pendiente','Pendiente'],['Activo','Activo'],['Finalizado','Finalizado']] %>
        </td>
      </tr>
    </table>
    <%= submit_tag "Search" %>
<% end %>
</div>
<br>

<div class="searchs">
<%= form_for($option, :url => "filter_by_capacity") do |f| %>
    <table border="0">
      <tr>
        <td width="150">
          Search all availables
        </td>
        <td width=150>
        </td>
      </tr>
    </table>
    <%= submit_tag "Search" %>
<% end %>
</div>
<br>

<br>


<div style="width:827px">
<%= link_to 'Back', logins_path %>

<table border="1" id="table">
  <tr style="background: silver">
    <th>Name</th>
      <th>Imagen</th>
      <th>Local</th>
      <th>Capacity</th>
      <th>Players</th>
      <th>Date and Time</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
  </tr>
<% @tournaments.each do |tournament|%>
  <tr>
    <td> <img src="http://2.bp.blogspot.com/-naNFMK1N26w/UDFNvkclXBI/AAAAAAAAAOg/ZmLmbDMRFss/s1600/gameday_reya.jpg" style="
    width: 73px;
    height: 107px;
" /> </td>
    <td><%= tournament.name %></td>
    <td><%= tournament.local.name %></td>
    <td align="center"><%= tournament.cant_part %></td>
    <td><%= tournament.fecha_hora %></td>
    <td><%= tournament.estado %></td>
    <td>
    
    </td>
      <td>
  
      </td>
    
  <tr>
<% end %>
</table>
</div>

magic/app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

magic/app/views/options/register_tournament.html.erb
<br>

<p>
	Tournament: <b><%= @member.tournament.name %></b>
</p>

<p>
	Member: <b><%= @member.user.name + ' ' + @member.user.paterno %></b>
</p>

<br>

<p>
	<%= @tournament_message %>
</p>

<%= link_to 'Back', options_path %>

magic/app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Opcion:</b>
  <%= @option.opcion %>
</p>

<p>
  <b>Local:</b>
  <%= @option.local %>
</p>

<p>
  <b>Estado:</b>
  <%= @option.estado %>
</p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>