magic/config/routes.rb
Magic::Application.routes.draw do

  resources :logins

  resources :options do
    member do
      get "register_tournament"
    end
  end

  resources :filters

  resources :comments do
    member do
      get "view_comment"
      get "add_comment"
      post "save_comment"
    end
  end

  resources :members do
    member do
      get "view_member"
    end
  end

  resources :districts
  resources :members

  resources :comments
  resources :tournaments

  resources :locals

  resources :users

  resources :districts

  get 'login' => 'users#login'

  match "filter_by_local" => "options#filter_by_local"
  match "filter_by_status" => "options#filter_by_status"
  match "filter_by_capacity" => "options#filter_by_capacity"

  match "validate_access" => "logins#validate_access"

end

magic/app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :local
  has_many :members
  has_many :coments


    validates :name, :presence => true
    validates :cant_part, :presence => true
    validates :local_id, :presence =>true
    validates :fecha_hora, :presence =>true
    validates :estado, :presence =>true
    validates_uniqueness_of :fecha_hora, :scope => :local_id



end

magic/app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tournaments }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tournament }
    end
  end

  # GET /tournaments/new
  # GET /tournaments/new.json
  def new
    @tournament = Tournament.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tournament }
    end
  end

  # GET /tournaments/1/edit
  def edit
    @tournament = Tournament.find(params[:id])
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(params[:tournament])
    @tournament.cantregis = 0

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render json: @tournament, status: :created, location: @tournament }
      else
        format.html { render action: "new" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tournaments/1
  # PUT /tournaments/1.json
  def update
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end
end

magic/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

magic/app/views/tournaments/_form.html.erb
<%= simple_form_for(@tournament) do |f| %>
   <%  f.error_notification %>


  <div class="field">

    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.label :cant_part %><br />
    <%= f.number_field :cant_part,:min => 1,:max => 8 %>
  </div>

 
  <div class="field">
    <%= f.label :fecha_hora %><br />
    <%= f.datetime_select :fecha_hora, :start_year => Time.now.year %>
  </div>
  <div class="field">

     <%= f.select :estado, [['Pendiente','Pendiente'],['Activo','Activo'],['Finalizado','Finalizado']] %>
  </div>
  <div class="field">
  
    <%= f.association :local %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

magic/app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

magic/app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table>
  <tr>
    <th>Name</th>

    <th>Local</th>
    <th>Capacity</th>
    <th>Date and Time</th>
    <th>Status</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tournaments.each do |tournament| %>
  <tr>

    <td><%= tournament.name %></td>
    <td><%= tournament.local.name %></td>
    <td align="center"><%= tournament.cant_part %></td>
    <td><%= tournament.fecha_hora %></td> 
    <td><%= tournament.estado %></td>
        

    <td><%= link_to 'Show', tournament %></td>
    <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
    <td><%= link_to 'Destroy', tournament, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tournament', new_tournament_path %>

magic/app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

magic/app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tournament.name %>
</p>

<p>
  <b>Cant part:</b>
  <%= @tournament.cant_part %>
</p>

<p>
  <b>Fecha hora:</b>
  <%= @tournament.fecha_hora %>
</p>

<p>
  <b>Estado:</b>
  <%= @tournament.estado %>
</p>

<p>
  <b>Local:</b>
  <%= @tournament.local.name %>
</p>


<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>

magic/app/views/tournaments/show_filters.html.erb
<%= form_tag controller_path, method: :get do %>
    <%= label_tag :option1 %>
    <%= radio_button_tag :option, "1" %>
    <br>
    <%= label_tag :option2 %>
    <%= radio_button_tag :option, "2" %>
    <br>
    <%= label_tag :option3 %>
    <%= radio_button_tag :option, "3" %>
    <br>
<%= submit_tag "Search", name: nil %>
<% end %>